package com.nesstation.app.core.storage

/**
 * ★ 街机封面搜索名映射器（驱动名 → libretro 英文标题）。
 *
 * 需求来源："街机应该读取扫描文件夹中实际 zip 文件名去下载封面"。
 * libretro 街机目录（FBNeo - Arcade Games / MAME）按**完整游戏标题**组织
 * （"Metal Slug 3.png"、"The King of Fighters '97.png"），zip 驱动名
 * （mslug3/kof97）直接搜不到。本表把常见驱动名映射到 libretro 收录的
 * **裸标题**（无序列号后缀 —— 裸标题文件在目录内普遍存在；带后缀的
 * 变体由 CoverFetcher.fuzzyMatch 的包含加分路径命中）。
 *
 * 未收录的驱动名原样返回（继续走模糊匹配）。
 */
object ArcadeCoverNames {

    private val DRIVER_TO_EN: Map<String, String> = mapOf(
        // ===== SNK 拳皇（The King of Fighters）=====
        "kof94" to "The King of Fighters '94",
        "kof94ea" to "The King of Fighters '94",
        "kof95" to "The King of Fighters '95",
        "kof95a" to "The King of Fighters '95",
        "kof96" to "The King of Fighters '96",
        "kof96ea" to "The King of Fighters '96",
        "kof97" to "The King of Fighters '97",
        "kof97a" to "The King of Fighters '97",
        "kof97h" to "The King of Fighters '97",
        "kof97pls" to "The King of Fighters '97",
        "kof98" to "The King of Fighters '98 - Dream Match Never Ends",
        "kof98a" to "The King of Fighters '98 - Dream Match Never Ends",
        "kof98h" to "The King of Fighters '98 - Dream Match Never Ends",
        "kof98k" to "The King of Fighters '98 - Dream Match Never Ends",
        "kof99" to "The King of Fighters '99",
        "kof99a" to "The King of Fighters '99",
        "kof99e" to "The King of Fighters '99",
        "kof99n" to "The King of Fighters '99",
        "kof99p" to "The King of Fighters '99",
        "kof2000" to "The King of Fighters 2000",
        "kof2000n" to "The King of Fighters 2000",
        "kof2001" to "The King of Fighters 2001",
        "kof2001h" to "The King of Fighters 2001",
        "kof2002" to "The King of Fighters 2002",
        "kof2002b" to "The King of Fighters 2002",
        "kof2002h" to "The King of Fighters 2002",
        "kof2003" to "The King of Fighters 2003",
        "kof2003h" to "The King of Fighters 2003",
        "kof10th" to "The King of Fighters 2002 (10th Anniversary)",
        "kof2k2um" to "The King of Fighters 2002 Unlimited Match",
        "kof98um" to "The King of Fighters '98 Ultimate Match",
        "kofxi" to "The King of Fighters XI",
        "kofxii" to "The King of Fighters XII",
        "kofxiii" to "The King of Fighters XIII",
        // ===== SNK 合金弹头（Metal Slug）=====
        "mslug" to "Metal Slug - Super Vehicle-001",
        "mslug4" to "Metal Slug 4",
        "mslug4p" to "Metal Slug 4 Plus",
        "mslug5" to "Metal Slug 5",
        "mslug5h" to "Metal Slug 5",
        "mslug6" to "Metal Slug 6",
        "mslugx" to "Metal Slug X - Super Vehicle-001",
        "mslug2" to "Metal Slug 2 - Super Vehicle-001_II",
        "mslug3" to "Metal Slug 3",
        "mslug3h" to "Metal Slug 3",
        // ===== SNK 其它 =====
        "samsho" to "Samurai Shodown",
        "samshoh" to "Samurai Shodown",
        "samsho2" to "Samurai Shodown II",
        "samsho2k" to "Samurai Shodown II",
        "samsho3" to "Samurai Shodown III",
        "samsho4" to "Samurai Shodown IV",
        "samsho5" to "Samurai Shodown V",
        "samsho5sp" to "Samurai Shodown V Special",
        "samsho6" to "Samurai Shodown VI",
        "fatfury1" to "Fatal Fury - King of Fighters",
        "fatfury2" to "Fatal Fury 2",
        "fatfury3" to "Fatal Fury 3 - Road to the Final Victory",
        "fatfursp" to "Fatal Fury Special",
        "garou" to "Garou - Mark of the Wolves",
        "garouh" to "Garou - Mark of the Wolves",
        "rbff1" to "Real Bout Fatal Fury",
        "rbff2" to "Real Bout Fatal Fury 2 - The Newcomers",
        "rbffspc" to "Real Bout Fatal Fury Special",
        "kizuna" to "Kizuna Encounter - Super Tag Battle",
        "savagere" to "Savage Reign",
        "wakuwak7" to "Waku Waku 7",
        "breakers" to "Breakers",
        "breakrev" to "Breakers Revenge",
        "neobombe" to "Neo Bomberman",
        "neodrift" to "Neo Drift Out - New Technology",
        "gowcaizr" to "Voltage Fighter - Gowcaizer",
        "wh1" to "World Heroes",
        "wh2" to "World Heroes 2",
        "wh2j" to "World Heroes 2 Jet",
        "whp" to "World Heroes Perfect",
        "lastblad" to "The Last Blade",
        "lastbladh" to "The Last Blade",
        "lastbld2" to "The Last Blade 2",
        "tophuntr" to "Top Hunter - Roddy & Cathy",
        "ncombat" to "Neo Turf Masters",
        "nblktop" to "Neo Bomberman",
        "joyjoy" to "Pochi and Nyaa",
        "zupapa" to "Zupapa!",
        // ===== Capcom =====
        "sf2" to "Street Fighter II - The World Warrior",
        "sf2ce" to "Street Fighter II' - Champion Edition",
        "sf2hf" to "Street Fighter II' - Hyper Fighting",
        "sf2t" to "Super Street Fighter II - The New Challengers",
        "sf2tb" to "Super Street Fighter II - The New Challengers",
        "sf2tj" to "Super Street Fighter II - The New Challengers",
        "sfz2al" to "Street Fighter Zero 2 Alpha",
        "sfzch" to "Street Fighter Zero 3",
        "sfz3" to "Street Fighter Zero 3",
        "sfz3a" to "Street Fighter Zero 3",
        "sfa" to "Street Fighter Alpha - Warriors' Dreams",
        "sfa2" to "Street Fighter Alpha 2",
        "sfa3" to "Street Fighter Alpha 3",
        "sfiii" to "Street Fighter III - New Generation",
        "sfiii2" to "Street Fighter III 2nd Impact - Giant Attack",
        "sfiii3" to "Street Fighter III 3rd Strike - Fight for the Future",
        "sfiii3n" to "Street Fighter III 3rd Strike - Fight for the Future",
        "sf4" to "Street Fighter IV",
        "xmcota" to "X-Men - Children of the Atom",
        "xmvsf" to "X-Men Vs. Street Fighter",
        "msh" to "Marvel Super Heroes Vs. Street Fighter",
        "mshvsf" to "Marvel Super Heroes Vs. Street Fighter",
        "mvsc" to "Marvel Vs. Capcom - Clash of Super Heroes",
        "mvsc2" to "Marvel Vs. Capcom 2 - New Age of Heroes",
        "mvsc2u" to "Marvel Vs. Capcom 2 - New Age of Heroes",
        "capsnk" to "Capcom Vs. SNK - Millennium Fight 2000",
        "capsnk2" to "Capcom Vs. SNK 2 - Mark of the Millennium 2001",
        "csclub" to "Capcom Sports Club",
        "ddtod" to "Dungeons & Dragons - Tower of Doom",
        "ddshadow" to "Dungeons & Dragons - Shadow over Mystara",
        "armwar" to "Armored Warriors",
        "awbash" to "Alien Vs. Predator",
        "avsp" to "Alien Vs. Predator",
        "dstlk" to "Darkstalkers - The Night Warriors",
        "vhunt2" to "Vampire Hunter 2 - Darkstalkers Revenge",
        "vsav" to "Vampire Savior - The Lord of Vampire",
        "vsav2" to "Vampire Savior 2 - The Lord of Vampire",
        "smbomb" to "Super Marvel Vs. Capcom",
        "maribro" to "Marvel Super Heroes",
        "strider" to "Strider Hiryu",
        "strider2" to "Strider 2",
        "ffight" to "Final Fight",
        "ffightj" to "Final Fight",
        "ffrevia" to "Final Fight Revenge",
        "captcomm" to "Captain Commando",
        "knights" to "Knights of the Round",
        "knightsh" to "Knights of the Round",
        "megaman" to "Mega Man - The Power Battle",
        "megaman2" to "Mega Man 2 - The Power Fighters",
        "megamans" to "Mega Man - The Power Battle",
        "1941" to "1941 - Counter Attack",
        "19xx" to "19XX - The War Against Destiny",
        "1944" to "1944 - The Loop Master",
        "varth" to "Varth - Operation Thunderstorm",
        "cawing" to "Carrier Air Wing",
        "msamurai" to "Mighty! Pang",
        "mpang" to "Mighty! Pang",
        "spf2t" to "Super Street Fighter II Turbo",
        "superman" to "Superman - The Man of Steel",
        "progear" to "Pro Gear no Arashi",
        "dimahoo" to "Dimahoo",
        "tgm2" to "Tetris The Grand Master 2 - The Absolute",
        "giggman" to "Gigaman",
        // ===== CPS3 =====
        "jojo" to "JoJo's Venture",
        "jojor" to "JoJo's Bizarre Adventure",
        "jojoba" to "JoJo's Bizarre Adventure",
        "redearth" to "Red Earth",
        // ===== 经典街机 =====
        "pacman" to "PuckMan (Japan set 1)",
        "pacmania" to "Pac-Mania",
        "puckman" to "PuckMan (Japan set 1)",
        "puckmana" to "PuckMan (Japan set 1)",
        "mspacman" to "Ms. Pac-Man",
        "pacmanf" to "Pac-Man - Gugeulpan",
        "dkong" to "Donkey Kong",
        "dkongjr" to "Donkey Kong Junior",
        "dkongx" to "Donkey Kong",
        "frogger" to "Frogger",
        "galaga" to "Galaga (Version A)",
        "galaxian" to "Galaxian (Version B)",
        "digdug" to "Dig Dug (Japan)",
        "digdugat" to "Dig Dug",
        "bublbobl" to "Bubble Bobble",
        "bublboblr" to "Bubble Bobble",
        "bubbob" to "Bubble Bobble",
        "boblbobl" to "Bubble Bobble",
        "snowbroj" to "Snow Bros. - Nick & Tom (Japan)",
        "snowbros" to "Snow Bros. - Nick & Tom",
        "snowbros2" to "Snow Bros. 2 - With New Elves",
        "punipuni" to "Puzzle & Action - PuniPuniBalloo",
        "toki" to "Toki - Going Ape Spit",
        "rampage" to "Rampage",
        "turtles" to "Teenage Mutant Ninja Turtles",
        "tmht" to "Teenage Mutant Ninja Turtles",
        "tmnt2" to "Teenage Mutant Ninja Turtles - Turtles in Time",
        "tmht2" to "Teenage Mutant Ninja Turtles - Turtles in Time",
        "tsuru" to "Turtle Ship",
        "ggpo" to "Skull & Crossbones",
        "crakwn" to "Crack Down",
        "wonder3" to "Wonder 3",
        "virtue" to "Virtua Fighter",
        "vf" to "Virtua Fighter",
        "vf2" to "Virtua Fighter 2",
        "vfkids" to "Virtua Fighter Kids",
        "vrally" to "V-Rally Edition 1999",
        "hook" to "Hook",
        "hsf2" to "Hyper Street Fighter 2 - The Anniversary Edition",
        "news" to "Downtown - Nekketsu Monogatari",
        // ===== 彩京/弹幕 =====
        "dogyuun" to "Dogyuun",
        "batrider" to "Armed Police Batrider",
        "batridera" to "Armed Police Batrider",
        "batsugun" to "Batsugun",
        "batsugna" to "Batsugun",
        "tfvark" to "Terra Cresta",
        "s1945" to "Strikers 1945",
        "s1945a" to "Strikers 1945",
        "s1945ii" to "Strikers 1945 II",
        "s1945iii" to "Strikers 1945 III",
        "s1945j" to "Strikers 1945",
        "dfeveron" to "Dangun Feveron",
        "gunbird" to "Gunbird",
        "gunbird2" to "Gunbird 2",
        "donpachi" to "DonPachi",
        "dodonpachi" to "DoDonPachi",
        "esprade" to "ESP Ra.De.",
        "guwange" to "Guwange",
        "saber" to "Sengoku Ace",
        "senkyu" to "Senkyu",
        "tengai" to "Tengai",
        // ===== IGS =====
        "pgm" to "Oriental Legend",
        "orientl" to "Oriental Legend",
        "orientl1" to "Oriental Legend",
        "kov" to "Knights of Valour",
        "kovplus" to "Knights of Valour Plus",
        "kov2" to "Knights of Valour 2",
        "kov2p" to "Knights of Valour 2 Plus",
        "kovsh" to "Knights of Valour - Sevengers",
        "sango" to "Knights of Valour - Sangoku Senki",
        "sgongi" to "Sengoku Giants",
        "drgw2" to "Dragon World II",
        "drgw3" to "Dragon World III",
        "photoy2k" to "Photo Y2K",
        "picolo" to "Photo Adventure",
        "moonlgh" to "Moonlight",
        "sximo" to "Xi You Shi E Zhuan Super",
        "orlegend" to "Oriental Legend",
        "puzzli2" to "Puzzli 2",
        // ===== 现代/其他 =====
        "tekken" to "Tekken",
        "tekken2" to "Tekken 2",
        "tekken3" to "Tekken 3",
        "tektagt" to "Tekken Tag Tournament",
        "soulclbr" to "Soul Calibur",
        "souledbr" to "Soul Edge",
        "beastor" to "Bloody Roar",
        "beastorz" to "Bloody Roar 2",
        "doapp" to "Dead or Alive++",
        "rvschool" to "Rival Schools - Evolution 2",
        "raizing" to "Battle Garegga",
        "batcir" to "Battle Circuit",
        "garegga" to "Battle Garegga",
        "blastoff" to "Blast Off",
        "trstar" to "Transfer Student",
        "ryujin" to "Ryu Jin",
        "samuraio" to "Samurai Aces",
        "kungfu" to "Kung-Fu Master",
        "sfexp" to "Street Fighter - The Battle Edition",
        "toutra" to "Thunder Dragon",
        "toutrun" to "OutRun",
        "outrun" to "OutRun",
        "afterbn2" to "After Burner II",
        "afterbur" to "After Burner",
        "swpower" to "Sonic Wings",
        "sonicwi" to "Sonic Wings",
        "sonicwi2" to "Sonic Wings 2",
        "sonicwi3" to "Sonic Wings 3",
        "turbo" to "Turbo",
        "gunsmoke" to "Gun.Smoke",
        "vulgus" to "Vulgus",
        "sonson" to "SonSon",
        "exedexes" to "Exed Exes",
        "sengekis" to "Sengoku Strikers",
        "sengoku" to "Sengoku Denshou",
        "sengoku2" to "Sengoku 2 - Sengoku Denshou 2",
        "sengoku3" to "Sengoku 3",
        "shocktrp" to "Shock Troopers",
        "shocktra" to "Shock Troopers - 2nd Squad",
        "lresort" to "Last Resort",
        "smshw2" to "Super Sidekicks 2 - The World Championship",
        "palamed" to "Palamedes",
        "joymach" to "Joyful Road",
        "algiers" to "Algiers",
        "cannonb" to "Cannon Ball",
        "maglord" to "Magical Lord",
        "socbrawl" to "Soccer Brawl",
        "superspy" to "The Super Spy",
        "mutnat" to "Mutation Nation",
        "sengokuh" to "Sengoku Denshou",
        "8ball" to "8 Ball Action",
        "2020bb" to "2020 Super Baseball",
        "3countb" to "3 Count Bout",
        "aof" to "Art of Fighting",
        "aof2" to "Art of Fighting 2",
        "aof3" to "Art of Fighting 3 - The Path of the Warrior",
        "alpham2" to "Alpha Mission II",
        "bstar" to "Baseball Stars Professional",
        "bstars2" to "Baseball Stars 2",
        "cyberlip" to "Cyber-Lip",
        "diggerma" to "Digger Man",
        "doubledr" to "Double Dragon",
        "fightfev" to "Fight Fever",
        "ghostlop" to "Ghostlop",
        "galaxyfg" to "Galaxy Fight - Universal Warriors",
        "ironclad" to "Ironclad",
        "janshin" to "Janshin Denshou",
        "kabukikl" to "Kabuki Klash - Far East of Eden",
        "kingofgl" to "King of the Monsters",
        "kingofg2" to "King of the Monsters 2",
        "league" to "League Bowling",
        "magdrop2" to "Magical Drop II",
        "magdrop3" to "Magical Drop III",
        "mahretsu" to "Mahjong Kyoretsuden",
        "minasan" to "Minasan no Okagesama Desu",
        "moneypee" to "Money Puzzle Exchanger",
        "mslug5p" to "Metal Slug 5 Plus",
        "nam1975" to "NAM-1975",
        "nitd" to "Nightmare in the Dark",
        "panicbom" to "Panic Bomber",
        "pgoal" to "Pleasure Goal - 5 on 5 Mini Soccer",
        "popbounc" to "Pop'n Bounce",
        "pspokes2" to "Power Spikes II",
        "quizdais" to "Quiz King of Fighters",
        "ridhero" to "Riding Hero",
        "roboarmy" to "Robo Army",
        "ssideki" to "Super Sidekicks",
        "ssideki2" to "Super Sidekicks 2",
        "ssideki3" to "Super Sidekicks 3 - The Next Glory",
        "ssideki4" to "The Ultimate 11 - SNK Football Championship",
        "stakwin" to "Stakes Winner",
        "stakwin2" to "Stakes Winner 2",
        "strhoop" to "Street Hoop - Street Slam",
        "twinsym" to "Twinkle Star Sprites",
        "viewpoin" to "Viewpoint",
        "wjudose" to "Windjammers",
        "xenoncr" to "Xenon Crisis",
        "zedblade" to "Zed Blade",
        "zintrick" to "ZinTrick"
    )

    /** 归一化驱动名（小写、去扩展名/路径/空白/下划线）。 */
    private fun normalizeDriver(name: String): String =
        name.trim()
            .substringAfterLast('/')
            .substringAfterLast('\\')
            .substringBeforeLast('.')
            .trim()
            .replace('_', ' ')
            .replace(Regex("\\s+"), " ")
            .lowercase()

    private val NORMALIZED: Map<String, String> = DRIVER_TO_EN.entries.associate {
        normalizeDriver(it.key) to it.value
    }

    /**
     * 驱动名（zip 主干）→ libretro 英文标题。
     * 未收录返回 null（调用方继续用原名走模糊匹配）。
     */
    fun lookup(driverName: String): String? {
        val key = normalizeDriver(driverName)
        NORMALIZED[key]?.let { return it }
        // 兜底：常见修改版后缀（h/p/k/a/b）剥离后再查一次（"kof98h" 类
        // 变体已显式收录；这里覆盖未显式收录的变体）
        val stripped = key.replace(Regex("\\s+(plus|turbo|hack)$"), "").trim()
        if (stripped != key) NORMALIZED[stripped]?.let { return it }
        return null
    }
}
